version: "3.7"

services:
  db:
    image: postgres:14.3
    env_file:
      - ./dotenv/db.env

  redis:
    image: redis:alpine
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: api
    image: saapie-api:latest
    env_file:
      - ./dotenv/api.env
    command: development
    volumes:
      - ./api:/home/node/saapie/api
    ports:
      - "5555:5555" # Prisma studio
    depends_on:
      - db

  vue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: vue
    image: saapie-vue:latest
    env_file:
      - ./dotenv/vue.env
    command: development
    volumes:
      - ./vue:/home/node/saapie/vue
    depends_on:
      - api

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./api/public:/usr/share/nginx/html/public
    ports:
      - "9000:80"
    depends_on:
      - vue
